version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: journey-mongodb
    restart: unless-stopped
    environment:
      # Uncomment and set these if you want authentication
      # MONGO_INITDB_ROOT_USERNAME: admin
      # MONGO_INITDB_ROOT_PASSWORD: yourpassword
      MONGO_INITDB_DATABASE: love_journey
    volumes:
      - mongodb_data:/data/db
    networks:
      - journey-network
    ports:
      - "27017:27017"  # Optional: expose MongoDB port for debugging

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: journey-backend
    restart: unless-stopped
    environment:
      PORT: 3000
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_DB: love_journey
      # Add these if using MongoDB authentication
      # MONGO_USER: admin
      # MONGO_PASS: yourpassword
    depends_on:
      - mongodb
    networks:
      - journey-network
    ports:
      - "3000:3000"

  # Frontend (Nginx)
  frontend:
    image: nginx:alpine
    container_name: journey-frontend
    restart: unless-stopped
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - journey-network
    ports:
      - "80:80"

networks:
  journey-network:
    driver: bridge

volumes:
  mongodb_data:
