version: '3.8'

services:
  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      PORT: ${BACKEND_PORT:-3000}
      MONGODB_URI: ${MONGODB_URI}
    networks:
      - coolify  # Use Coolify's default network where MongoDB lives

  # Frontend (Nginx)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - NGINX_PORT=80
    depends_on:
      - backend
    networks:
      - coolify  # Same network
    labels:
      - "coolify.port=80"

networks:
  coolify:  # This is Coolify's default network
    external: true
    name: coolify
